/// Flutter icons EcommerceAppUI
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EcommerceAppUI
///      fonts:
///       - asset: fonts/EcommerceAppUI.ttf
///
///
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
///
import 'package:flutter/widgets.dart';

class UiIcons {
  UiIcons._();

  static const _kFontFam = 'EcommerceAppUI';

  static const IconData home = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData facebook_circled = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData twitter_circled = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData trash_1 = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData alarm_clock = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData atomic = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData settings_1 = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData settings_2 = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData shopping_cart = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData trash = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData bar_chart = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData favorites = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData filter = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData battery = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData cloud_computing_1 = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData eraser = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData file = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData fast_forward = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData chat = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData file_2 = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData book = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData cloud = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData bell = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData calculator = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData file_1 = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData box = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData chat_1 = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData car = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData download = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData calendar = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData credit_card = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData cloud_computing = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData laptop = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData cutlery = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData checked = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData folder_1 = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData cursor = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData envelope = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData compass = const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData megaphone = const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData loupe = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData layers = const IconData(0xe834, fontFamily: _kFontFam);
  static const IconData flag = const IconData(0xe835, fontFamily: _kFontFam);
  static const IconData eye = const IconData(0xe836, fontFamily: _kFontFam);
  static const IconData idea = const IconData(0xe837, fontFamily: _kFontFam);
  static const IconData battery_1 = const IconData(0xe838, fontFamily: _kFontFam);
  static const IconData file_3 = const IconData(0xe839, fontFamily: _kFontFam);
  static const IconData id_card = const IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData folder = const IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData bluetooth = const IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData message_1 = const IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData music = const IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData message_2 = const IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData like = const IconData(0xe840, fontFamily: _kFontFam);
  static const IconData next = const IconData(0xe841, fontFamily: _kFontFam);
  static const IconData power_button = const IconData(0xe842, fontFamily: _kFontFam);
  static const IconData planet_earth = const IconData(0xe843, fontFamily: _kFontFam);
  static const IconData pause = const IconData(0xe844, fontFamily: _kFontFam);
  static const IconData play_button = const IconData(0xe845, fontFamily: _kFontFam);
  static const IconData phone_call = const IconData(0xe846, fontFamily: _kFontFam);
  static const IconData presentation = const IconData(0xe847, fontFamily: _kFontFam);
  static const IconData image = const IconData(0xe848, fontFamily: _kFontFam);
  static const IconData information = const IconData(0xe849, fontFamily: _kFontFam);
  static const IconData inbox = const IconData(0xe84a, fontFamily: _kFontFam);
  static const IconData message = const IconData(0xe84b, fontFamily: _kFontFam);
  static const IconData line_chart = const IconData(0xe84c, fontFamily: _kFontFam);
  static const IconData gamepad = const IconData(0xe84d, fontFamily: _kFontFam);
  static const IconData key = const IconData(0xe84e, fontFamily: _kFontFam);
  static const IconData money = const IconData(0xe84f, fontFamily: _kFontFam);
  static const IconData microphone = const IconData(0xe850, fontFamily: _kFontFam);
  static const IconData map = const IconData(0xe851, fontFamily: _kFontFam);
  static const IconData paint_brush = const IconData(0xe852, fontFamily: _kFontFam);
  static const IconData mail = const IconData(0xe853, fontFamily: _kFontFam);
  static const IconData medal = const IconData(0xe854, fontFamily: _kFontFam);
  static const IconData monitor = const IconData(0xe855, fontFamily: _kFontFam);
  static const IconData photo_camera = const IconData(0xe856, fontFamily: _kFontFam);
  static const IconData video_camera = const IconData(0xe857, fontFamily: _kFontFam);
  static const IconData printer = const IconData(0xe858, fontFamily: _kFontFam);
  static const IconData reload = const IconData(0xe859, fontFamily: _kFontFam);
  static const IconData padlock_1 = const IconData(0xe85a, fontFamily: _kFontFam);
  static const IconData speakers = const IconData(0xe85b, fontFamily: _kFontFam);
  static const IconData user_3 = const IconData(0xe85c, fontFamily: _kFontFam);
  static const IconData placeholder = const IconData(0xe85d, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe85e, fontFamily: _kFontFam);
  static const IconData padlock = const IconData(0xe85f, fontFamily: _kFontFam);
  static const IconData safebox = const IconData(0xe860, fontFamily: _kFontFam);
  static const IconData zoom_out = const IconData(0xe861, fontFamily: _kFontFam);
  static const IconData trophy = const IconData(0xe862, fontFamily: _kFontFam);
  static const IconData rss = const IconData(0xe863, fontFamily: _kFontFam);
  static const IconData upload = const IconData(0xe864, fontFamily: _kFontFam);
  static const IconData shield = const IconData(0xe865, fontFamily: _kFontFam);
  static const IconData zoom_in = const IconData(0xe866, fontFamily: _kFontFam);
  static const IconData return_icon = const IconData(0xe867, fontFamily: _kFontFam);
  static const IconData user_1 = const IconData(0xe868, fontFamily: _kFontFam);
  static const IconData user_2 = const IconData(0xe869, fontFamily: _kFontFam);
  static const IconData wifi = const IconData(0xe86a, fontFamily: _kFontFam);
  static const IconData users = const IconData(0xe86b, fontFamily: _kFontFam);
  static const IconData smartphone = const IconData(0xe86c, fontFamily: _kFontFam);
  static const IconData car_1 = const IconData(0xe8aa, fontFamily: _kFontFam);
  static const IconData bowling = const IconData(0xe8ab, fontFamily: _kFontFam);
  static const IconData books = const IconData(0xe8ac, fontFamily: _kFontFam);
  static const IconData cosmetics = const IconData(0xe8ae, fontFamily: _kFontFam);
  static const IconData dress = const IconData(0xe8af, fontFamily: _kFontFam);
  static const IconData drug = const IconData(0xe8b1, fontFamily: _kFontFam);
  static const IconData feeding_bottle = const IconData(0xe8b4, fontFamily: _kFontFam);
  static const IconData fitness = const IconData(0xe8b5, fontFamily: _kFontFam);
  static const IconData game = const IconData(0xe8b6, fontFamily: _kFontFam);
  static const IconData garden = const IconData(0xe8b7, fontFamily: _kFontFam);
  static const IconData gift = const IconData(0xe8b8, fontFamily: _kFontFam);
  static const IconData glasses = const IconData(0xe8ba, fontFamily: _kFontFam);
  static const IconData home_cinema = const IconData(0xe8bc, fontFamily: _kFontFam);
  static const IconData jacket = const IconData(0xe8be, fontFamily: _kFontFam);
  static const IconData jewelry = const IconData(0xe8bf, fontFamily: _kFontFam);
  static const IconData kitchen = const IconData(0xe8c0, fontFamily: _kFontFam);
  static const IconData living_room = const IconData(0xe8c2, fontFamily: _kFontFam);
  static const IconData microphone_1 = const IconData(0xe8c3, fontFamily: _kFontFam);
  static const IconData nail = const IconData(0xe8c4, fontFamily: _kFontFam);
  static const IconData pet_care = const IconData(0xe8c5, fontFamily: _kFontFam);
  static const IconData piano = const IconData(0xe8c6, fontFamily: _kFontFam);
  static const IconData restaurant = const IconData(0xe8c7, fontFamily: _kFontFam);
  static const IconData salon = const IconData(0xe8c9, fontFamily: _kFontFam);
  static const IconData shoe = const IconData(0xe8cb, fontFamily: _kFontFam);
  static const IconData shoe_1 = const IconData(0xe8cc, fontFamily: _kFontFam);
  static const IconData spa = const IconData(0xe8ce, fontFamily: _kFontFam);
  static const IconData sport = const IconData(0xe8cf, fontFamily: _kFontFam);
  static const IconData teddy_bear = const IconData(0xe8d0, fontFamily: _kFontFam);
  static const IconData tent = const IconData(0xe8d1, fontFamily: _kFontFam);
  static const IconData tool = const IconData(0xe8d3, fontFamily: _kFontFam);
  static const IconData vacuum = const IconData(0xe8d4, fontFamily: _kFontFam);
  static const IconData watch = const IconData(0xe8d5, fontFamily: _kFontFam);
  static const IconData baby_changing = const IconData(0xe8d7, fontFamily: _kFontFam);
  static const IconData bakery = const IconData(0xe8d8, fontFamily: _kFontFam);
  static const IconData bedroom = const IconData(0xe8d9, fontFamily: _kFontFam);
}
